apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentmanagerservice
  labels:
    app: docserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docserver
  template:
    metadata:
      labels:
        app: docserver
    spec:
      containers:
        - name: documentmanagerservice
          image: hkanjih/docserver:latest
          volumeMounts:
            - mountPath: "/files/UploadedFiles"
              name: volume-file
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
      volumes:
        - name: volume-file
          persistentVolumeClaim:
            claimName: doc-server-disk
---
apiVersion: v1
kind: Service
metadata:
  name: documentmanagerservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: docserver