apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;

    events {
          worker_connections  10240;
    }

    http {
       server {
           listen       80;
           listen  [::]:80;
           server_name  localhost;

           root /www/data;

           location / {
               root   /usr/share/nginx/html;
               index  index.html index.htm;
           }

           location /images/ {
               autoindex on;
           }

           #error_page  404              /404.html;

           # redirect server error pages to the static page /50x.html
           #
           error_page   500 502 503 504  /50x.html;
           location = /50x.html {
               root   /usr/share/nginx/html;
           }
       }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentmanagerservice
  labels:
    app: docserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docserver
  template:
    metadata:
      labels:
        app: docserver
    spec:
      containers:
        - name: documentmanagerservice
          image: hkanjih/docserver:latest
          volumeMounts:
            - mountPath: "/files/UploadedFiles"
              name: volume-file
          ports:
            - containerPort: 3000
          env:
            - name: ASPNETCORE_URLS
              value: http://*:3000
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - mountPath: "/www/data/images"
              name: volume-file
            - mountPath: /etc/nginx/nginx.conf # mount nginx-conf volume to /etc/nginx
              subPath: nginx.conf
              readOnly: true
              name: nginx-conf
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
      volumes:
        - name: volume-file
          persistentVolumeClaim:
            claimName: doc-server-disk
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: documentmanagerservice
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      name: api
    - port: 80
      name: nginx
  selector:
    app: docserver