apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-server-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs-simple"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi